### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by nesl247** [pr-triage/pr-triage#46]
### Summary

The bot does not seem to be doing anything. I have it installed on a test repo, and no matter what, it does not label anything. Neither a needs-review, or reviewed and needs to be fixed, nothing.

I also looked at the one PR opened on this project, and it doesn't look like the bot is being used here, or it isn't working.

**Comment by sotayamashita** [comment]
@nesl247 I fixed it. It failed because GitHub's event is different. You can see the diff. https://github.com/pr-triage/pr-triage/pull/47. I am going to think about how to avoid these kinds of errors.

**Comment by sotayamashita** [comment]
@nesl247 I would appreciate if you could close this issue after checking this app  works in your test repo.

**Comment by nesl247** [comment]
To be clear, neither the "needs review", "changes requested" nor "commented" seem to be working.

**Comment by sotayamashita** [comment]
@nesl247 

>It does not appear to be working. You deployed the fix correct?

Yes I did.

> To be clear, neither the "needs review", "changes requested" nor "commented" seem to be working.

I have tried with new repository. https://github.com/watsonbot/test-pr-triage/pull/1#pullrequestreview-132698513 . Is it possible to share your repository?

**Comment by nesl247** [comment]
Unfortunately not as it is a private repo. I just tested by uninstalling the bot and reinstalling it, and the issue is still present.

Could it be the bot is broken with private repositories somehow? Or maybe it's with organizations?

I created a public repo on my own user (not in my organization where I am having the problem) and it worked.

**Comment by sotayamashita** [comment]
@nesl247 

> Could it be the bot is broken with private repositories somehow? Or maybe it's with organizations?

Oh. It might be a clue to solve the problem. I'll try it!

> I created a public repo on my own user (not in my organization where I am having the problem) and it worked.

I appreciate your kind.

**Comment by nesl247** [comment]
Sure. Let me know what you need me to do to test.

**Comment by nesl247** [comment]
I was able to fix the issue in the linked PR. Hopefully you can merge and deploy it soon. My company is excited to use the bot.

**Comment by nesl247** [comment]
Looks like the fix is working. Thanks @sotayamashita.

**Comment by sotayamashita** [comment]
I appreciate your kind help. :bow:
